DEVICE     = atmega328p
CLOCK      = 16000000
OBJECTS    = lib/mcp2515/src/spi.o lib/mcp2515/src/mcp2515.o
# generated by http://www.engbedded.com/fusecalc/
# clockout at PORTB0
FUSES      = -U lfuse:w:0xbe:m -U hfuse:w:0xd9:m -U efuse:w:0x07:m

TARGETS = dos template

LIB =
LIBINCLUDE =
INCLUDE = -Ilib/mcp2515/src
FLAGS = $(LIB) $(LIBINCLUDE) $(INCLUDE)

AVRDUDE = avrdude -p$(DEVICE)
COMPILE = avr-gcc -Wall -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE)

PUR = \033[0;35m
NC = \033[0m

.PHONY: clean fuse

.INTERMEDIATE: $(addsuffix .elf, $(TARGETS))

all:	$(addsuffix .elf, $(TARGETS)) $(addsuffix .avr-size, $(TARGETS))

objects: $(OBJECTS)

%.o:	%.c
	$(COMPILE) -c $< -o $@ $(FLAGS) 

%.flash-usbasp:	%.hex
		sudo $(AVRDUDE) -cusbasp -U flash:w:$<

fuse:
	sudo $(AVRDUDE) -cusbasp $(FUSES)

clean:
	rm -f $(addsuffix .hex, $(TARGETS)) $(addsuffix .elf, $(TARGETS)) $(addprefix src/, $(addsuffix .o, $(TARGETS))) $(OBJECTS) src/lib/hausbus_protocols.o

%.elf:
	echo "$(PUR)Copying handlers$(NC)"
	cp -f src/$(basename $@).h src/lib/handler.h
	echo "$(PUR)Building main file$(NC)"
	make --always-make src/$(basename $@).o
	echo "$(PUR)Building protocol handler$(NC)"
	make --always-make src/lib/hausbus_protocols.o
	echo "$(PUR)Building other objects$(NC)"
	make objects
	echo "$(PUR)Building $(basename $@) binary$(NC)"
	$(COMPILE) -o $@ $(OBJECTS) src/$(basename $@).o src/lib/hausbus_protocols.o

%.hex: %.elf
	rm -f $@
	avr-objcopy -j .text -j .data -O ihex $< $@

%.avr-size: %.elf
	echo "$(PUR)$(basename $@) binary$(NC)"
	avr-size $< --mcu=$(DEVICE) --format=avr
